const unpayData = {
  'orderID':'00_CAAFC5F33FDA9B3A',
  'isPay':false,
  'pageTitle':'我的另一半报告',
  'keyWord':[
    '享受生活',
    '吃苦耐劳',
    '嘴硬心软',
    '慢热闷骚'
  ],
  'scoreTitle':'我的感情观',
  'sex':false,
  'name':'hjk',
  'birthday':'1990-05-05',
  'birthTimeHour':'9:30:00',
  'data':[
    {
      'titleCode':2,
      'content':'',
      'title':'我的感情弱点',
      'contentUnLockTitle':'我会因为什么感情弱点伤害彼此？'
    },
    {
      'titleCode':3,
      'content':'',
      'title':'感情弱点建议',
      'contentUnLockTitle':'感情专家的情感建议'
    },
    {
      'titleCode':4,
      'content':'',
      'title':'豪门潜质',
      'contentUnLockTitle':'我能嫁入豪门吗？'
    },
    {
      'titleCode':5,
      'content':'',
      'contentTwo':'',
      'title':'另一半模样',
      'contentUnLockTitle':'我的另一半是什么模样?',
      'contentUnLockTwoTitle':'我在哪里能够遇到另一半？'
    },
    {
      'titleCode':6,
      'content':'',
      'contentTwo':'',
      'title':'婚后感情生活',
      'contentUnLockTitle':'提前预知我们的感情波折点',
      'contentUnLockTwoTitle':'感情专家支招稳定感情关系秘诀',
      'score':'3',
      'twoscore':'1.5'
    },
    {
      'titleCode':7,
      'content':[
        {
          'title':'另一半财富指数',
          'score':3,
          'dataContent':'TA希望自己的财富能由自己支配，但也并不代表TA不愿意与你分享。'
        },
        {
          'title':'另一半体贴指数',
          'score':4.5,
          'dataContent':'因为你比较害羞，和人相处也很内敛，TA可能会对你很体贴。'
        },
        {
          'title':'另一半浪漫指数',
          'score':2.5,
          'dataContent':'TA是大胆而直接表达自己的感情的人，而且比较缺乏耐心，并不是很浪漫的人。'
        },
        {
          'title':'另一半顾家指数',
          'score':1.5,
          'dataContent':'TA是一个非常成功并且事业心强的人，由于这个关系所以可能并不是很顾家。'
        }
      ]
    }
  ]
}

const payedData = {
  'data':{
    'orderID':'00_D0379C5ECBF00B1B',
    'isPay':true,
    'pageTitle':'我的另一半报告',
    'keyWord':[
      '沟通才华',
      '天马行空',
      '广交朋友',
      '随性乐观'
    ],
    'scoreTitle':'我的感情观',
    'sex':false,
    'name':'dsfg',
    'birthday':'1990-12-01',
    'birthTimeHour':'23:30:00',
    'data':[
      {
        'titleCode':2,
        'content':'你看待事物和感情是有自己的一套标准和想法的，就像在工作中，你会严格按照自己设定的标准来执行和约束自己，并朝着自己的方向持续不停的努力来达到最终的安稳。在恋爱中也是这样，你希望自己的恋爱能够满足自己的标准和高度，对方最好能够与你形成共鸣和匹配，比如，有相同的价值观，对美食有相同的追求等；期待在生活上、精神上有良好化学反应，因此，你会习惯去衡量双方的匹配度，如果你觉得对方达不到跟你一致的标准，你会产生不那么爱TA的心态——这些都会影响你感情的稳定性。',
        'title':'我的感情弱点',
        'contentUnLockTitle':'我会因为什么感情弱点伤害彼此？'
      },
      {
        'titleCode':3,
        'content':'不要太苛刻于对方是不是跟你有一样的喜好或者追求；对于失去或者错过的，不要太过于计较得失，有时候放下就是一种成长和蜕变；也不要太过于追求安稳的结果，有时候放开标准可能还会产生更多奇妙的，出乎意料之外的收获。',
        'title':'感情弱点建议',
        'contentUnLockTitle':'感情专家的情感建议'
      },
      {
        'titleCode':4,
        'content':'你在意的不是金钱的本身多少，而是在意通过金钱换来的不错的经历和刺激体验，你需要通过金钱来实现你那些天马行空的想法；你有着出色的沟通能力，你的随性乐观也很容易吸引到志同道合的条件不错的他，因此，你需要找到一位有趣的人陪你一起玩耍；处于恋爱阶段的你，建议和异性朋友间保持一点距离，不然过分亲密的举止会让你的伴侣产生一些不安全感。不妨和恋人一起制定旅行计划，也是相互增进感情的过程。',
        'title':'豪门潜质',
        'contentUnLockTitle':'我能嫁入豪门吗？'
      },
      {
        'titleCode':5,
        'content':'TA亲和力满分， 为人直爽，不喜欢一切的条条框框，喜欢自由。对方喜欢倾诉但不爱留意他人的讲话，喜欢新生事物，喜欢旅游，有精神探求且讲求独立性。',
        'contentTwo':'你们的缘分属于千里姻缘一线牵的类型。彼此的身价背景、身份事业完全不搭界，差了很多且你们出生地相距遥远。你们可能是朋友介绍认识或者去参加聚会认识，在认识的当天聊得很愉快，非常聊得来，那么这就可能是你的缘分。建议你们多多分享彼此感受，相处起来会很愉快。',
        'title':'另一半模样',
        'contentUnLockTitle':'我的另一半是什么模样?',
        'contentUnLockTwoTitle':'我在哪里能够遇到另一半？'
      },
      {
        'titleCode':6,
        'content':'你是外貌协会，对物质要求并不高，但容易遇人不淑。你带给对方是一种浪漫的感觉，容易处处留情，对方如果没有特别明朗且吸引你的点，你可能会无视对方，因为你在感情上的触觉粗枝大叶，体察不到对方的感受。但一旦你稳定下来，还是比较安定的。',
        'contentTwo':'你们是被动的组合，关系中充满想象，像是生活在精神世界的一对。对方常常沉静在自己的内心世界，你得必须学会接受，实际上你自己常常也处于迷茫中，看不清自己的需要。建议你们都要在实际中感受生活的一切。',
        'title':'婚后感情生活',
        'contentUnLockTitle':'提前预知我们的感情波折点',
        'contentUnLockTwoTitle':'感情专家支招稳定感情关系秘诀',
        'score':'3',
        'twoscore':'1'
      },
      {
        'titleCode':7,
        'content':[
          {
            'title':'另一半财富指数',
            'score':2.5,
            'dataContent':'TA会积极争取自己的利益，但是在花钱方面比较冲动，挣得多花得也比较多。'
          },
          {
            'title':'另一半体贴指数',
            'score':4.5,
            'dataContent':'你待人温柔和善，非常招TA喜欢，因为你的性格，TA对你也比较体贴。'
          },
          {
            'title':'另一半浪漫指数',
            'score':2.5,
            'dataContent':'TA总是让人捉摸不透，有时能为你营造浪漫气氛，有时又情绪低落对你不理不睬。'
          },
          {
            'title':'另一半顾家指数',
            'score':1.5,
            'dataContent':'你们的关系过于被动，TA平时喜欢独处且不善沟通，家庭方面并不是很美满。'
          }
        ]
      }
    ]
  },
  'status':0,
  'msg':''
}
const data = {
  unpayData,
  payedData
}
export default data;